import { ENEMY_INITIAL_HEALTH } from "./Enemy.constants"

export const SHIELD_SIZE = 100
export const ROTATE_VALUES = [-20, -15, -10, 10, 15, 20]
export const SHIELD_MOVE_DELAY = 1000
export const SHIELD_MOVE_DURATION = 500
export const SHIELD_REMOVE_DELAY = 500
export const SHIELD_TRANSFORM_DURATION = 200

export const SHIELD_HEALTH_RATIO = 3
export const INITIAL_SHIELD_HEALTH = ENEMY_INITIAL_HEALTH / SHIELD_HEALTH_RATIO